apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 236351108871.dkr.ecr.us-east-1.amazonaws.com/frontend:fec57cdd47fc5e95e91f49b68ca5eaf9b6c25347
          ports:
            - containerPort: 3000
