name: ci-fullstack-backend-ci

# Manual trigger
on:
  workflow_dispatch:

  push:
    branches: 
      - main
      #comment this later--------------------#
  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    paths:
      - 'starter/backend/**'
    branches:
      - main


jobs:
  test_job:

    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository.
     
      - uses: actions/checkout@v3

      # Set up a Node.js environment using the specified node version.
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # install dependencies
      - run: cd starter/backend && pip install pipenv 

      # INstall 
      - run: cd starter/backend && pipenv install


     #Run the testa
      - run: cd starter/backend && pipenv run test
      


  lint_job:
    runs-on: ubuntu-latest
    steps:    
       # Check out the code from the repository.
     
      - uses: actions/checkout@v3

      # Set up a python environment using the specified  version.
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

       # install dependencies
      - run: cd starter/backend && pip install pipenv 

      - run: cd starter/backend && pip install flake8
      - run: cd starter/backend && flake8 .

      # INstall 
      - run: cd starter/backend && pipenv install
      - name: Run Linting
        run: cd starter/backend && pipenv run lint

  build_job: 
    runs-on: ubuntu-latest
    
    needs: [test_job, lint_job]

    steps:
        # checkout of code from repo
     - name: checkout code
       uses: actions/checkout@v3
     # - name: python setup
     #    # Set up a python environment using the specified  version.
     #   uses: actions/setup-python@v4
     #   with:
     #      python-version: "3.10"
     # - name: Build and Run
     #   run: cd starter/backend && pip install pipenv && pipenv install && pipenv run serve
          

        
     - name: docker image
       run: |
          cd starter/backend  # Navigate to the backend directory
          docker build --tag=mp-backend:latest .

     
