name: ci-fullstack-workflow

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  workflow_dispatch:

  push:
    branches: 
      - main
  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    paths:
      - 'starter/frontend/**'
    branches:
      - main

#Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  test_job:

    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository.
     
      - uses: actions/checkout@v3

      # Set up a Node.js environment using the specified node version.
      - uses: actions/setup-node@v3
        with:
          node-version: latest

      # Run the tests.
      - run: cd starter/frontend && npm ci

     #Run the testa
      - run: cd starter/frontend && CI=true npm test
      

      # # run the linting
      # - run: cd starter/frontend && npm run lint
        

  lint_job:
    runs-on: ubuntu-latest
    steps:    
       # Check out the code from the repository.
     
      - uses: actions/checkout@v3

      # Set up a Node.js environment using the specified node version.
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Run Linting
        run: cd starter/frontend && npm ci && npm run lint

        
