name: ci-fullstack-workflow

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  workflow_dispatch:

  push:
    branches: 
      - main

#Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository.
      - run: cd starter/frontend
      - uses: actions/checkout@v3

      # Set up a Node.js environment using the specified node version.
      - uses: actions/setup-node@v3
        with:
          node-version: latest

      # Install the dependencies.
      - run:  npm ci

      # check thw preseent working directory
      - run: pwd

      # Run the tests.
      - run: npm test --passWithNoTests

      # Run the linter.
      - run: npm run lint

      # Send a console message at completion.
      - run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."

        
